// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt_sc-zK12jDPV-Yz-LQdZdHbgynIOh38',
    appId: '1:213222081592:web:355e3a8554230b1d7a92cd',
    messagingSenderId: '213222081592',
    projectId: 'eventhive-47b68',
    authDomain: 'eventhive-47b68.firebaseapp.com',
    storageBucket: 'eventhive-47b68.appspot.com',
    measurementId: 'G-C1FSW4P7MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnBJT2ga-kCwFz_c9YpgId5x9flN1rFMI',
    appId: '1:213222081592:android:d68b249f6880b9fa7a92cd',
    messagingSenderId: '213222081592',
    projectId: 'eventhive-47b68',
    storageBucket: 'eventhive-47b68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD49nGBhd7EjJoXHnzdanIW_kxyKhYK7i0',
    appId: '1:213222081592:ios:e61b8277d89e3fc27a92cd',
    messagingSenderId: '213222081592',
    projectId: 'eventhive-47b68',
    storageBucket: 'eventhive-47b68.appspot.com',
    iosBundleId: 'com.example.eventhive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD49nGBhd7EjJoXHnzdanIW_kxyKhYK7i0',
    appId: '1:213222081592:ios:e61b8277d89e3fc27a92cd',
    messagingSenderId: '213222081592',
    projectId: 'eventhive-47b68',
    storageBucket: 'eventhive-47b68.appspot.com',
    iosBundleId: 'com.example.eventhive',
  );
}
